# Generated by Django 4.2.3 on 2023-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('BirthDate', models.DateField(null=True)),
            ],
        ),
    ]
