# Generated by Django 4.2.3 on 2023-08-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthdate',
            new_name='BirthDate',
        ),
    ]
