# Generated by Django 4.2.3 on 2023-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_remove_client_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('Area', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('reception_pieces', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('other_information', models.TextField(blank=True)),
            ],
        ),
    ]
