# Generated by Django 4.2.3 on 2023-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='apartment_type',
            field=models.CharField(choices=[('Fully Finish', 'Fully Finish'), ('Semi Finish', 'Semi Finish'), ('Other', 'Other')], default='Fully Finish', max_length=30),
        ),
        migrations.AddField(
            model_name='flat',
            name='other_apartment_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
