# Generated by Django 4.2.3 on 2023-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_flat_apartment_type_flat_other_apartment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='location',
            field=models.CharField(choices=[('October', 'October'), ('Hadayiq October', 'Hadayiq October'), ('Hadayiq Alahram', 'Hadayiq Alahram'), ('Sheikh Zayed', 'Sheikh Zayed')], default='Unknown', max_length=30),
        ),
    ]
