# Generated by Django 4.2.3 on 2023-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_flat_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Stage1', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage2', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage3', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage4', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage5', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage6', models.CharField(blank=True, max_length=50, null=True)),
                ('Stage7', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
