# Generated by Django 4.2.3 on 2023-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_adminfill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminFill',
        ),
        migrations.AddField(
            model_name='client',
            name='Stage1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stage7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Password',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='UserName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
