# Generated by Django 4.2.3 on 2024-05-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_delete_adminfill_client_stage1_client_stage2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flat',
        ),
    ]
