# Generated by Django 4.2.3 on 2024-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_delete_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('Dtype', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('hba1c', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('blood_pressure', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('pregnant', models.BooleanField(default=False)),
            ],
        ),
    ]
